Update rust version
It is needed to be able to update the dependencies versions.
Without the rust version change we get following kind of an error:

  error: cannot install package `cargo-nextest 0.9.97`, \
    it requires rustc 1.85 or newer, while the currently active rustc version is 1.84.1